# Repo info
mariadb_mirror: 'yum.mariadb.org'
mariadb_version: '5.5'

# packages
mariadb_packages:
  - MariaDB-server
  - MariaDB-client
  - MySQL-python

# Login / users
mariadb_new_root_password: "d@123456"
mariadb_root_password: ""
mariadb_users: {name: "usr_mariadb", password: "d@123456", priv: "*.*:ALL,GRANT"}

# General conf
mariadb_configure_swappiness: true
mariadb_swappiness: 0
mariadb_character_set_server: utf8
mariadb_collation_server: utf8_general_ci
mariadb_base_dir: "/usr"
mariadb_charsets_dir: "/usr/share/mysql/charsets"
mariadb_config: "/etc/my.cnf.d/my.cnf"
mariadb_data_dir: "/var/lib/mysql"
mariadb_install_db_bin: "/usr/bin/mysql_install_db"
mariadb_long_query_time: 10
mariadb_pid: "/var/run/mysqld/mysqld.pid"
mariadb_server_id: 1
mariadb_share_dir: "/usr/share/mysql"
mariadb_skip_charset_handshake: true
# mariadb_service: "/usr/sbin/mysqld"



# Network configuration
mariadb_bind_address: '127.0.0.1'
mariadb_port: 3306
mariadb_skip_networking: false
mariadb_socket: "/var/run/mysqld/mysqld.sock"

# Service configuration
# mariadb_max_connect_errors: 10
# mariadb_max_connections: 505
# mariadb_max_user_connections: 500
# mariadb_skip_name_resolve: 1
# mariadb_wait_timeout: 60

# Logging
mariadb_log_bin: false
mariadb_mysql_errorlog: "/var/log/mysql/mysql.err"
mariadb_mysqld_errorlog: "/var/log/mysql/mysqld.err"
mariadb_mysqld_slowlog: "/var/log/mysql/mysqld.slow"

# Query cache
mariadb_query_cache_limit: false  # 128K
mariadb_query_cache_size: false   # 64M


# System resources
mariadb_join_buffer_size: '128k'
mariadb_max_allowed_packet: '4M'
mariadb_max_heap_table_size: '16M'
mariadb_open_files_limit: '65353'
mariadb_read_buffer_size: '128k'
mariadb_read_rnd_buffer_size: '256k'
mariadb_sort_buffer_size: '2M'
mariadb_table_definition_cache: '1400'
mariadb_table_open_cache: '2000'
mariadb_table_open_cache_instances: '8'
mariadb_thread_cache_size: 50
mariadb_tmp_table_size: '16M'
