# packages
glpi_prerequisites_packages:
  - php-gd
  - php-mbstring
  - php-curl
  - php-ldap
  - php-xmlrpc
  - php
  - php-cli
  - php-common
  - php-devel
  - php-fpm
  - php-gd
  - php-ldap
  - php-mbstring
  - php-pdo
  - php-pear
  - php-xml
  - php-xmlrpc
  - httpd
  - php-openssl
  - php-mysql
  - mod_auth_gssapi # LDAP integration

php_default_version: "5.4.16"

httpd_service: "httpd"
firewalld_service: "firewalld"