---
- name: Open port 80 for http access
  firewalld:
    service: http
    permanent: true
    state: enabled
  become: yes

- name: Restart the firewalld service to load in the firewall changes
  service: 
    name: firewalld 
    state: restarted
  become: yes

# Generates warning message and always changed output
- name: Ensure service is started 
  shell: service httpd start
  become: yes
  args:
    warn: False