---
# - name: Ensure service is started didn't work!!!
#   service:
#     name: "{{ mariadb_service }}"
#     state: started
#     enabled: yes
#   tags: mariadb
#   become: yes

# Generates warning message and always changed output
- name: Ensure service is started 
  shell: service mysql start
  become: yes
  args:
    warn: False