---
 #Change httpd root path
- lineinfile:
    path: "/etc/httpd/conf/httpd.conf"
    regexp: "^DocumentRoot "
    line: "DocumentRoot \"/var/www\""
  become: yes

- name: Open port 80 for http access
  firewalld:
    service: http
    permanent: true
    state: enabled
  become: yes

- name: Restart the firewalld service to load in the firewall changes
  service: 
    name: firewalld 
    state: restarted
  become: yes

# Generates warning message and always changed output
- name: Restart httpd service
  shell: service httpd restart
  become: yes
  args:
    warn: False