---
# Copy database dump file to remote host and restore it to database 'my_db'
- name: Copy database dump file
  copy:
    src: "files/{{ mariadb_dump_file }}"
    dest: "/tmp/{{ mariadb_dump_file }}"

- name: Unpack glpi
  unarchive:
    src: "/tmp/{{ mariadb_dump_file }}"
    dest: "/tmp"
    remote_src: yes
  become: yes

- name: Restore database
  mysql_db:
    name: glpi
    state: import
    target: "/tmp/{{ mariadb_sql_file }}"
    login_user: root
    login_password: "{{ mariadb_new_root_password }}"
  become: yes

- name: Drop unnecessaries databases
  mysql_db:
    name: "{{ item }}"
    state: absent
    login_user: root
    login_password: "{{ mariadb_new_root_password }}"
  with_items: "{{ mariadb_unnecessary_databases }}"